# """
# ******************************************************************************
# settings
# ******************************************************************************
# """

PARAM_MODEL:
  f_in: 2
  f_out: 1
  f_hid: 64
  depth: 5
  act: "gelu"
  w_init: "Glorot"
  b_init: "zeros"
  inv: False

PARAM_OPTIM:
  optim: "Adam"
  lr: .001

PARAM_DN:
  flag: False
  tau: 10
  beta: .999
